# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
##### plugins versions #####

# Spring Boot 3.4.x의 최신 버전 #
spring-boot-v3dot4-plugin = "3.4.4"

# https://github.com/spring-gradle-plugins/dependency-management-plugin
spring-dependency-management-plugin = "1.1.7"


##### libraries versions #####
# https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies
spring-cloud-dependencies = "2024.0.1"

### WebJars ###
# https://mvnrepository.com/artifact/org.webjars/webjars-locator
# webjars-locator는 Boot Dependencies에 있는 webjars-locator-core를 그대로 쓰면 된다.
# https://mvnrepository.com/artifact/org.webjars/jquery
webjars-jquery = "3.7.1"
# https://mvnrepository.com/artifact/org.webjars/bootstrap
webjars-bootstrap = "5.3.3"



[libraries]
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud-dependencies" }

webjars-jquery = { module = "org.webjars:jquery", version.ref = "webjars-jquery" }
webjars-bootstrap = { module = "org.webjars:bootstrap", version.ref = "webjars-bootstrap" }



[plugins]
spring-boot-v3dot4 = { id = "org.springframework.boot", version.ref = "spring-boot-v3dot4-plugin" }

spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management-plugin" }
